class_name: ConvNet3d
### Dataset Configuration
model_config: 
    d1: 25
    d2: 25
    dt: 60
    conv_layers: [[5, 5, 5, 3, 32], [5, 5, 5, 32, 64]]
    fc_layers: [512, 2]
    keep_prob: .8
    t_downsample: 2
    bn: False
