class_name: ConvNet2d
### Dataset Configuration
model_config: 
    d1: 25
    d2: 25
    conv_layers: [[5, 5, 3, 32], [5, 5, 32, 64], [5, 5, 64, 128]]
    fc_layers: [512, 2]
    keep_prob: .8
    bn: False
