class_name: ConvNet3d
### Dataset Configuration
model_config: 
    d1: 25
    d2: 25
    dt: 60
    conv_layers: [[5, 3, 3, 3, 32], [5, 3, 3, 32, 64],[5, 3, 3, 64, 128]]
    fc_layers: [512, 2]
    keep_prob: 1
    t_downsample: 2
    bn: True
