class_name: EncDec
### Dataset Configuration
model_config: 
    dec_rnn_hid_dim: 128
    decoder_time_size: 20
    batch_size: 64
    ## encoder
    encoder_input_shape: 
    enc_rnn_hid_dim: 128
    # stochasticity
    decoder_init_noise: 'dropout' # {'gaussian', 'dropout'}
    noise_level: .3 ## 1-keep_value
    decoder_input_keep_prob: .5