node1: &batch_size 64


class_name: EncDec
### Dataset Configuration
model_config: 
    dec_rnn_hid_dim: 16
    decoder_time_size: 20
    batch_size: *batch_size
    ## encoder
    encoder_input_shape: [*batch_size, 1, 4]
    enc_rnn_hid_dim: 16
    keep_prob: 1.
    fc_layers: [16]