class_name: Seq2Seq
### Dataset Configuration
model_config: 
    d1: 100
    d2: 50
    conv_layers: [[3, 3, 4, 16], [3, 3, 16, 32], [3,3,32,64]]
    fc_layers: [64,2]
    keep_prob: 1.
    rnn_hid_dim: 256
    encoder_time_size: 1
    decoder_time_size: 20
    batch_size: 32