## look at 2*window_radius segment
## if > count_threshold points has p > prob_threshold:
##   PNR detected
class: RunWindowP
detect_config:
    type: 'fixed'
    window_radius: 30
    prob_threshold: .3
    count_threshold: 7
