## look at 2*window_radius segment
## if > count_threshold points has p > prob_threshold:
##   PNR detected
detect_config:
    type: 'fixed'
    window_radius: 8
    prob_threshold: .8
    count_threshold: 5 

