max_iters: 100000
schedulers:
  lrv:
    class: ConstantStepMultiplyScheduler
    kwargs:
      type: 'float'
      init_value: .05
      every_N_step: 10000
      factor: .5
  tfs:
    class: ConstantStepIncrementScheduler
    kwargs:
      type: 'int'
      init_value: 20
      every_N_step: 10000
      increment: -1
      clamp: [1,20]
#  fts2:
#    class: LinearStepIncrementScheduler
#    kwargs:
#      type: 'int'
#      init_value: 20
#      final_value: 0
#      increment: -1
#      clamp: [1,20]
